### ISSUE TITLE
How i can edit CLC files?

### ISSUE THREAD

**Issue by crazymember** [AllTheHaxx/Lua-Scripts#11]
Hello
i downloaded some CLC files but they have some problem that i can fix them if i can edit them but i cant edit them. they wont open currently in notepad can anyone help me please how can i edit .CLC files?

**Comment by Henningstone** [comment]
The point of CLCs is that you can not edit them, hence it's impossible. Also, I really advise against using both CLCs and old versions of ATH that can still run CLCs because they are insecure, for which reason this system has been removed in later versions.

**IMPORTANT**: official CLCs are no longer being distributed since half a year or more now, so if you downloaded them from a website recently, it's likely that they are malicious (contain viruses)!
